version: 0.2

env:
  variables:
    PYTHON_ENV: "test"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Start prebuild phase

  build:
    commands:
      - echo Running unit tests with pytest
      - pytest --junitxml=reports/test-results.xml --tb=short

  post_build:
    commands:
      - 'if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then echo "Build OK"; else echo "Build en echec"; fi'
      - echo Finished at $(date)

reports:
  pytest_reports:
    files:
      - "test-results.xml"
    base-directory: reports
    file-format: JUNITXML

artifacts:
  files:
    - '**/*'
  base-directory: .